{
 "title": "Cortex / Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values(kube_pod_container_info{image=~\".*cortex.*\"}, namespace)"
    }
   },
   { "name": "timewindow", "label": "Time window width", "query": "1m, 2m, 3m, 4m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "API proxy /api/v1/push, POSTs, rate by status code ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(cortex_api_proxy_request_duration_seconds_count{job=\"$tenant-tenant.cortex-api\",method=\"POST\",route=\"api_v1_push\"}[$timewindow]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Queries through Grafana, request duration ($timewindow mean) by status code",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "duration [s]" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(grafana_datasource_request_duration_seconds_sum{namespace=\"$tenant-tenant\", datasource=\"metrics\"}[$timewindow]) / rate(grafana_datasource_request_duration_seconds_count{namespace=\"$tenant-tenant\", datasource=\"metrics\"}[$timewindow]))\n"
    }
   ]
  },
  {
   "title": "Ingester CPU util (%), all tenants (mean over $timewindow)",
   "type": "graph",
   "description": "100 % is one CPU core",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPU util [%]" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{namespace=\"cortex\", container=\"ingester\"}[$timewindow])*100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "API proxy /api/v1/push, 2xx-acked POSTs, request duration, event rate [1/s] ($timewindow mean)",
   "type": "heatmap",
   "description": "I think this total duration includes reading the request body.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (le) (rate(cortex_api_proxy_request_duration_seconds_bucket{job=\"$tenant-tenant.cortex-api\",method=\"POST\",status_code=~\"200|202\",route=\"api_v1_push\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "API proxy /api/prom/query[_range], GETs, rate by status code ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(cortex_api_proxy_request_duration_seconds_count{job=\"$tenant-tenant.cortex-api\",method=\"GET\",route=~\"api_prom_api_v1_query.*\"}[$timewindow]))"
    }
   ]
  },
  {
   "title": "Ingester mem (WSS)",
   "type": "graph",
   "description": "For context see https://www.bwplotka.dev/2019/golang-memory-monitoring/",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "bytes", "label": "WSS" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"cortex\", container=\"ingester\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "distributor: tenant: $tenant, sample recv rate ($timewindow mean)",
   "type": "graph",
   "description": "before rejection, validation?",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "receive rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_distributor_received_samples_total{user=\"$tenant\"}[$timewindow]))",
     "legendFormat": "recv sample rate"
    },
    {
     "expr": "sum(rate(cortex_distributor_non_ha_samples_received_total[$timewindow]))",
     "legendFormat": "recv sample rate (\"non-HA\")"
    }
   ]
  },
  {
   "title": "API proxy /api/v1/query, 200-acked GETs, request duration, event rate [1/s] ($timewindow mean)",
   "type": "heatmap",
   "description": "I think this total duration includes reading the request body.",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "sum by (le) (rate(cortex_api_proxy_request_duration_seconds_bucket{job=\"$tenant-tenant.cortex-api\",method=\"GET\",status_code=\"200\",route=~\"api_v1_query\"}[$timewindow]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "distributor CPU util (%), all tenants (mean over $timewindow)",
   "type": "graph",
   "description": "100 % is one CPU core",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "CPU util [%]" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total{namespace=\"cortex\", container=\"distributor\"}[$timewindow])*100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "distributor: all tenants, ingester append rate  ($timewindow mean)",
   "type": "graph",
   "description": "the counter is increased while reading the request body, before validation, and before passing things on to the ingester.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "append rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (ingester) (rate(cortex_distributor_ingester_appends_total[$timewindow]))",
     "legendFormat": "ingester {{ingester}}"
    }
   ]
  },
  {
   "title": "total rate of cortex_distributor_ingester_queries (?)",
   "type": "graph",
   "description": "unclear what that is",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_distributor_ingester_queries_total[$timewindow]))"
    }
   ]
  },
  {
   "title": "distributor mem (WSS)",
   "type": "graph",
   "description": "For context see https://www.bwplotka.dev/2019/golang-memory-monitoring/",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "WSS" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"cortex\", container=\"distributor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "distributor, all tenants, POSTs, HTTP response rate by status code ($timewindow mean)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (status_code) (rate(cortex_request_duration_seconds_count{job=\"cortex.distributor\", method=\"POST\"}[$timewindow]))"
    }
   ]
  },
  {
   "title": "compactors: total number of blocks in storage bucket, for tenant $tenant",
   "type": "graph",
   "description": "Includes blocks marked for deletion, but not partial blocks",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cortex_bucket_blocks_count{namespace=\"cortex\", user=\"$tenant\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ingester, all tenants,  sample failure rate (?) ($timewindow mean)",
   "type": "graph",
   "description": "unclear what that is",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "error rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cortex_ingester_ingested_samples_failures_total[$timewindow]))"
    }
   ]
  },
  {
   "title": "ingester: rate of ingested samples, all tenants (mean over $timewindow)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(cortex_ingester_ingested_samples_total[$timewindow]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ingesters: total number of uploaded TSDB blocks, all tenants",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cortex_ingester_shipper_uploads_total{namespace=\"cortex\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "distributor replication factor, by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short", "label": "rate [1/s]" }
   ],
   "targets": [
    {
     "expr": "cortex_distributor_replication_factor{namespace=\"cortex\", job=\"cortex.distributor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ingesters: number of series in memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    { "expr": "cortex_ingester_memory_series", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "ingesters: total number of chunks in the TSDB head block, all tenants",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "cortex_ingester_tsdb_head_chunks",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ingester flush queue length per instance (all tenants)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short", "label": "queue length" }
   ],
   "targets": [
    {
     "expr": "cortex_ingester_flush_queue_length{job=\"cortex.ingester\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ingesters: total number of chunks in the TSDB head block, all tenants",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "cortex_ingester_tsdb_storage_blocks_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}